FROM microsoft/aspnet:latest
SHELL ["powershell", "-command"]

COPY ["./bad-web-app/","/inetpub/wwwroot/"]

# Allow IIS write to Data folder
RUN	icacls C:\inetpub\wwwroot\Data /grant IIS_IUSRS:F


# Create local admin user
RUN net user admin P@ssw0rd! /ADD; \
	net localgroup Administrators admin /ADD
	

# Ton tunnuksen lukeminen serviceltä.